import React, { useState } from 'react';
import {
  X,
  Sparkles,
  TrendingUp,
  TrendingDown,
  Minus,
  Lightbulb,
  BookOpen,
  Users,
  BarChart3,
  Copy,
  Check,
  Download,
  Share2,
  Cpu,
  Layers,
  HelpCircle,
  Clock,
  ArrowRight,
} from 'lucide-react';
import { NewsArticle, SimplifiedNews } from '../types';
import { AudioPlayer } from './AudioPlayer';

interface SimplificationModalProps {
  article: NewsArticle | null;
  simplified: SimplifiedNews | null;
  isOpen: boolean;
  onClose: () => void;
  onSelectJargonTerm?: (term: string) => void;
}

export const SimplificationModal: React.FC<SimplificationModalProps> = ({
  article,
  simplified,
  isOpen,
  onClose,
  onSelectJargonTerm,
}) => {
  const [activeTab, setActiveTab] = useState<
    'overview' | 'jargon' | 'impact' | 'personas' | 'comparison'
  >('overview');
  const [copied, setCopied] = useState(false);

  if (!isOpen || !simplified) return null;

  const handleCopyMarkdown = () => {
    const md = `# ${simplified.headline}

## TL;DR Summary
${simplified.tldr.map((t) => `- ${t}`).join('\n')}

## Layman Analogy (ELI5)
${simplified.eli5}

## Market Impact
- **Sentiment:** ${simplified.marketImpact.sentiment.toUpperCase()} (Score: ${simplified.marketImpact.impactScore}/10)
- **Key Drivers:** ${simplified.marketImpact.keyDrivers.join(', ')}
- **Affected Sectors:** ${simplified.marketImpact.affectedSectors.join(', ')}
- **Potential Winners:** ${simplified.marketImpact.winners.join(', ')}
- **Potential Losers:** ${simplified.marketImpact.losers.join(', ')}

## Jargon Buster
${simplified.jargonGlossary
  .map(
    (j) => `### ${j.term}
- **Definition:** ${j.definition}
- **Analogy:** ${j.simpleExample}`
  )
  .join('\n\n')}

## Persona Takeaways
- **Retail Investor:** ${simplified.personaTakeaways.retailInvestor}
- **Student:** ${simplified.personaTakeaways.student}
- **General Public:** ${simplified.personaTakeaways.generalPublic}

---
*Generated by FinNews AI (${simplified.modelUsed}) in ${simplified.processingTimeMs}ms*`;

    navigator.clipboard.writeText(md);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const text = `FINNEWS AI - FINANCIAL INTELLIGENCE REPORT
=============================================
HEADLINE: ${simplified.headline}
SOURCE: ${article?.source || 'Financial Press'}
DATE: ${simplified.createdAt}
AI MODEL: ${simplified.modelUsed} (${simplified.processingTimeMs}ms)

1. EXECUTIVE TL;DR:
${simplified.tldr.map((t, i) => `   ${i + 1}. ${t}`).join('\n')}

2. LAYMAN ANALOGY (ELI5):
   ${simplified.eli5}

3. MARKET IMPACT:
   Sentiment: ${simplified.marketImpact.sentiment.toUpperCase()} (Impact Score: ${simplified.marketImpact.impactScore}/10)
   Drivers: ${simplified.marketImpact.keyDrivers.join(', ')}
   Sectors: ${simplified.marketImpact.affectedSectors.join(', ')}
   Winners: ${simplified.marketImpact.winners.join(', ')}
   Losers:  ${simplified.marketImpact.losers.join(', ')}

4. JARGON GLOSSARY:
${simplified.jargonGlossary.map((j) => `   * ${j.term}: ${j.definition}\n     Example: ${j.simpleExample}`).join('\n\n')}

5. STAKEHOLDER TAKEAWAYS:
   [Retail Investors]: ${simplified.personaTakeaways.retailInvestor}
   [Finance Students]: ${simplified.personaTakeaways.student}
   [General Public]:   ${simplified.personaTakeaways.generalPublic}
`;
    const blob = new Blob([text], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `finnews-summary-${Date.now()}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const getSentimentColor = (sentiment: string) => {
    switch (sentiment) {
      case 'bullish':
        return 'text-emerald-700 bg-emerald-50 border-emerald-200';
      case 'bearish':
        return 'text-rose-700 bg-rose-50 border-rose-200';
      default:
        return 'text-amber-700 bg-amber-50 border-amber-200';
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-3 sm:p-6 bg-slate-900/40 backdrop-blur-xs overflow-y-auto">
      <div className="relative w-full max-w-4xl bg-white border border-slate-200 rounded-2xl shadow-xl overflow-hidden my-auto max-h-[90vh] flex flex-col text-slate-800">
        {/* Top Sticky Header */}
        <div className="p-5 sm:p-6 border-b border-slate-200 bg-white/95 sticky top-0 z-10">
          <div className="flex items-center justify-between gap-3 mb-2">
            <div className="flex items-center gap-2 flex-wrap text-xs text-slate-500">
              <span className="font-semibold text-emerald-700 flex items-center gap-1">
                <Sparkles className="w-3.5 h-3.5 text-emerald-600" />
                Simplified Intelligence
              </span>
              <span aria-hidden="true" className="text-slate-300">·</span>
              <span className="font-medium text-slate-700">{article?.source || 'Financial Press'}</span>
              <span aria-hidden="true" className="text-slate-300">·</span>
              <span className="font-mono text-[11px] text-slate-500 flex items-center gap-1">
                <Cpu className="w-3 h-3 text-indigo-500" />
                {simplified.modelUsed} ({simplified.processingTimeMs}ms)
              </span>
            </div>

            <div className="flex items-center gap-1.5">
              <button
                onClick={handleCopyMarkdown}
                className="p-1.5 rounded-lg text-slate-500 hover:text-slate-900 hover:bg-slate-100 transition-colors cursor-pointer"
                title="Copy Markdown Summary"
              >
                {copied ? <Check className="w-4 h-4 text-emerald-600" /> : <Copy className="w-4 h-4" />}
              </button>

              <button
                onClick={handleDownload}
                className="p-1.5 rounded-lg text-slate-500 hover:text-slate-900 hover:bg-slate-100 transition-colors cursor-pointer"
                title="Download Briefing Report"
              >
                <Download className="w-4 h-4" />
              </button>

              <button
                onClick={onClose}
                className="p-1.5 rounded-lg text-slate-500 hover:text-slate-900 hover:bg-slate-100 transition-colors cursor-pointer"
                title="Close modal"
              >
                <X className="w-5 h-5" />
              </button>
            </div>
          </div>

          <h2 className="text-xl sm:text-2xl font-bold text-slate-900 tracking-tight leading-snug font-['Plus_Jakarta_Sans']">
            {simplified.headline}
          </h2>

          {/* Navigation Tabs - Clean Segmented Control */}
          <div className="flex items-center gap-1 mt-4 p-1 bg-slate-100 rounded-xl overflow-x-auto scrollbar-none">
            <button
              onClick={() => setActiveTab('overview')}
              className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium whitespace-nowrap transition-colors cursor-pointer ${
                activeTab === 'overview'
                  ? 'bg-white text-slate-900 shadow-2xs font-semibold'
                  : 'text-slate-600 hover:text-slate-900'
              }`}
            >
              <Lightbulb className="w-3.5 h-3.5 text-amber-500" />
              <span>Overview & ELI5</span>
            </button>

            <button
              onClick={() => setActiveTab('jargon')}
              className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium whitespace-nowrap transition-colors cursor-pointer ${
                activeTab === 'jargon'
                  ? 'bg-white text-slate-900 shadow-2xs font-semibold'
                  : 'text-slate-600 hover:text-slate-900'
              }`}
            >
              <BookOpen className="w-3.5 h-3.5 text-indigo-500" />
              <span>Jargon Buster ({simplified.jargonGlossary.length})</span>
            </button>

            <button
              onClick={() => setActiveTab('impact')}
              className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium whitespace-nowrap transition-colors cursor-pointer ${
                activeTab === 'impact'
                  ? 'bg-white text-slate-900 shadow-2xs font-semibold'
                  : 'text-slate-600 hover:text-slate-900'
              }`}
            >
              <BarChart3 className="w-3.5 h-3.5 text-sky-500" />
              <span>Market Impact</span>
            </button>

            <button
              onClick={() => setActiveTab('personas')}
              className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium whitespace-nowrap transition-colors cursor-pointer ${
                activeTab === 'personas'
                  ? 'bg-white text-slate-900 shadow-2xs font-semibold'
                  : 'text-slate-600 hover:text-slate-900'
              }`}
            >
              <Users className="w-3.5 h-3.5 text-purple-500" />
              <span>Who It Affects</span>
            </button>

            <button
              onClick={() => setActiveTab('comparison')}
              className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium whitespace-nowrap transition-colors cursor-pointer ${
                activeTab === 'comparison'
                  ? 'bg-white text-slate-900 shadow-2xs font-semibold'
                  : 'text-slate-600 hover:text-slate-900'
              }`}
            >
              <Layers className="w-3.5 h-3.5 text-slate-500" />
              <span>Original vs AI</span>
            </button>
          </div>
        </div>

        {/* Modal Scrollable Body */}
        <div className="p-5 sm:p-6 overflow-y-auto space-y-6 flex-1">
          {/* Audio Player Strip */}
          <AudioPlayer script={simplified.audioScript} title={simplified.headline} />

          {/* TAB 1: OVERVIEW & ELI5 */}
          {activeTab === 'overview' && (
            <div className="space-y-6 animate-in fade-in duration-150">
              {/* TL;DR Key Takeaways */}
              <div className="bg-slate-50 border border-slate-200/80 rounded-2xl p-5 sm:p-6">
                <div className="flex items-center gap-2 mb-3.5">
                  <span className="w-2 h-2 rounded-full bg-emerald-600" />
                  <h3 className="text-xs font-bold uppercase tracking-wider text-slate-700">
                    Executive Summary (TL;DR)
                  </h3>
                </div>
                <ul className="space-y-3 text-sm text-slate-700">
                  {simplified.tldr.map((bullet, idx) => (
                    <li key={idx} className="flex items-start gap-3">
                      <span className="w-5 h-5 rounded-full bg-emerald-100 text-emerald-800 flex items-center justify-center font-mono text-xs font-semibold shrink-0 mt-0.5">
                        {idx + 1}
                      </span>
                      <span className="leading-relaxed">{bullet}</span>
                    </li>
                  ))}
                </ul>
              </div>

              {/* Layman Analogy / ELI5 Callout */}
              <div className="bg-amber-50/80 border border-amber-200/80 rounded-2xl p-5 sm:p-6 shadow-2xs">
                <div className="flex items-center gap-2 mb-2 text-amber-800 font-semibold text-xs uppercase tracking-wider">
                  <Lightbulb className="w-4 h-4 text-amber-600" />
                  <span>Explain Like I'm 5 (Everyday Analogy)</span>
                </div>
                <p className="text-sm text-amber-950 leading-relaxed italic">
                  "{simplified.eli5}"
                </p>
              </div>

              {/* Key Numerical Metrics Grid */}
              {simplified.keyMetrics && simplified.keyMetrics.length > 0 && (
                <div>
                  <h3 className="text-xs font-bold uppercase tracking-wider text-slate-500 mb-3">
                    Key Numbers Decoded
                  </h3>
                  <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3">
                    {simplified.keyMetrics.map((km, i) => (
                      <div
                        key={i}
                        className="bg-slate-50 border border-slate-200/80 rounded-xl p-4 flex flex-col justify-between"
                      >
                        <span className="text-xs text-slate-500 font-medium mb-1">{km.label}</span>
                        <span className="text-lg font-bold font-mono text-emerald-700 mb-1">{km.value}</span>
                        <span className="text-xs text-slate-600 leading-snug">{km.significance}</span>
                      </div>
                    ))}
                  </div>
                </div>
              )}
            </div>
          )}

          {/* TAB 2: JARGON BUSTER */}
          {activeTab === 'jargon' && (
            <div className="space-y-4 animate-in fade-in duration-150">
              <div>
                <h3 className="text-sm font-bold text-slate-900">Jargon Buster Dictionary</h3>
                <p className="text-xs text-slate-500">
                  Complex Wall Street and economic terms translated into plain human English.
                </p>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {simplified.jargonGlossary.map((item, idx) => (
                  <div
                    key={idx}
                    className="bg-white border border-slate-200 hover:border-indigo-200 rounded-xl p-4.5 transition-colors shadow-2xs flex flex-col justify-between"
                  >
                    <div>
                      <div className="flex items-center justify-between mb-2">
                        <span className="font-bold text-sm text-indigo-900">{item.term}</span>
                        <span className="text-[11px] font-mono text-slate-400">
                          #{idx + 1}
                        </span>
                      </div>
                      <p className="text-xs text-slate-700 font-medium mb-3 leading-relaxed">
                        {item.definition}
                      </p>
                      <div className="text-xs text-slate-600 bg-slate-50 p-3 rounded-lg border border-slate-100 mb-3 leading-relaxed">
                        <span className="text-slate-800 font-semibold block mb-0.5">Context in this news:</span>
                        {item.contextExplanation}
                      </div>
                    </div>

                    <div className="text-xs text-emerald-900 bg-emerald-50 p-2.5 rounded-lg border border-emerald-100">
                      <span className="font-semibold block text-emerald-800 text-[11px] uppercase tracking-wider mb-0.5">
                        Simple Example:
                      </span>
                      {item.simpleExample}
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* TAB 3: MARKET IMPACT */}
          {activeTab === 'impact' && (
            <div className="space-y-6 animate-in fade-in duration-150">
              {/* Impact Meter */}
              <div className="bg-slate-50 border border-slate-200 rounded-2xl p-5 sm:p-6">
                <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 mb-4">
                  <div>
                    <h3 className="text-sm font-bold text-slate-900 mb-1">Market Sentiment & Impact Score</h3>
                    <p className="text-xs text-slate-500">
                      AI assessment of directional market pressure and macro significance.
                    </p>
                  </div>
                  <div className="flex items-center gap-3">
                    <span
                      className={`px-2.5 py-1 rounded-md text-xs font-bold uppercase tracking-wider border ${getSentimentColor(
                        simplified.marketImpact.sentiment
                      )}`}
                    >
                      {simplified.marketImpact.sentiment}
                    </span>
                    <span className="text-xl font-bold font-mono text-slate-900">
                      {simplified.marketImpact.impactScore}
                      <span className="text-xs text-slate-500 font-normal">/10 Impact</span>
                    </span>
                  </div>
                </div>

                {/* Score Bar */}
                <div className="w-full bg-slate-200 h-2 rounded-full overflow-hidden mb-4">
                  <div
                    className={`h-full rounded-full transition-all duration-500 ${
                      simplified.marketImpact.sentiment === 'bullish'
                        ? 'bg-emerald-600'
                        : simplified.marketImpact.sentiment === 'bearish'
                        ? 'bg-rose-600'
                        : 'bg-amber-600'
                    }`}
                    style={{ width: `${simplified.marketImpact.impactScore * 10}%` }}
                  />
                </div>

                {/* Key Drivers */}
                <div>
                  <h4 className="text-xs font-semibold text-slate-600 uppercase tracking-wider mb-2">
                    Primary Market Drivers
                  </h4>
                  <div className="flex flex-wrap gap-2">
                    {simplified.marketImpact.keyDrivers.map((driver, i) => (
                      <span
                        key={i}
                        className="px-2.5 py-1 rounded-md text-xs font-medium bg-white text-slate-700 border border-slate-200 shadow-2xs"
                      >
                        {driver}
                      </span>
                    ))}
                  </div>
                </div>
              </div>

              {/* Sectors, Winners & Losers */}
              <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                <div className="bg-slate-50 border border-slate-200 rounded-xl p-4.5">
                  <h4 className="text-xs font-bold uppercase tracking-wider text-sky-700 mb-3">
                    Affected Sectors
                  </h4>
                  <ul className="space-y-1.5 text-xs text-slate-700">
                    {simplified.marketImpact.affectedSectors.map((sector, i) => (
                      <li key={i} className="flex items-center gap-2">
                        <span className="w-1.5 h-1.5 rounded-full bg-sky-500" />
                        <span>{sector}</span>
                      </li>
                    ))}
                  </ul>
                </div>

                <div className="bg-emerald-50/60 border border-emerald-200/80 rounded-xl p-4.5">
                  <h4 className="text-xs font-bold uppercase tracking-wider text-emerald-800 mb-3 flex items-center gap-1.5">
                    <TrendingUp className="w-3.5 h-3.5 text-emerald-600" /> Likely Winners
                  </h4>
                  <ul className="space-y-1.5 text-xs text-slate-700">
                    {simplified.marketImpact.winners.map((winner, i) => (
                      <li key={i} className="flex items-center gap-2">
                        <span className="w-1.5 h-1.5 rounded-full bg-emerald-600" />
                        <span>{winner}</span>
                      </li>
                    ))}
                  </ul>
                </div>

                <div className="bg-rose-50/60 border border-rose-200/80 rounded-xl p-4.5">
                  <h4 className="text-xs font-bold uppercase tracking-wider text-rose-800 mb-3 flex items-center gap-1.5">
                    <TrendingDown className="w-3.5 h-3.5 text-rose-600" /> Likely Losers
                  </h4>
                  <ul className="space-y-1.5 text-xs text-slate-700">
                    {simplified.marketImpact.losers.map((loser, i) => (
                      <li key={i} className="flex items-center gap-2">
                        <span className="w-1.5 h-1.5 rounded-full bg-rose-600" />
                        <span>{loser}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              </div>
            </div>
          )}

          {/* TAB 4: PERSONAS */}
          {activeTab === 'personas' && (
            <div className="space-y-4 animate-in fade-in duration-150">
              <div className="bg-slate-50 border border-slate-200 rounded-xl p-5">
                <div className="flex items-center gap-2 text-emerald-700 font-bold text-sm mb-2">
                  <TrendingUp className="w-4 h-4" />
                  <span>For Retail Investors (Stocks, ETFs, 401k)</span>
                </div>
                <p className="text-sm text-slate-700 leading-relaxed">
                  {simplified.personaTakeaways.retailInvestor}
                </p>
              </div>

              <div className="bg-slate-50 border border-slate-200 rounded-xl p-5">
                <div className="flex items-center gap-2 text-indigo-700 font-bold text-sm mb-2">
                  <BookOpen className="w-4 h-4" />
                  <span>For Economics & Finance Students</span>
                </div>
                <p className="text-sm text-slate-700 leading-relaxed">
                  {simplified.personaTakeaways.student}
                </p>
              </div>

              <div className="bg-slate-50 border border-slate-200 rounded-xl p-5">
                <div className="flex items-center gap-2 text-amber-800 font-bold text-sm mb-2">
                  <Users className="w-4 h-4 text-amber-600" />
                  <span>For Everyday Consumers (Jobs, Mortgages, Inflation)</span>
                </div>
                <p className="text-sm text-slate-700 leading-relaxed">
                  {simplified.personaTakeaways.generalPublic}
                </p>
              </div>
            </div>
          )}

          {/* TAB 5: RAW VS AI COMPARISON */}
          {activeTab === 'comparison' && (
            <div className="space-y-4 animate-in fade-in duration-150">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div className="bg-slate-50 border border-slate-200 rounded-xl p-4 flex flex-col">
                  <span className="text-xs font-bold uppercase tracking-wider text-rose-700 mb-2">
                    Original Financial News Text (Dense / Jargon-Heavy)
                  </span>
                  <div className="text-xs text-slate-700 leading-relaxed font-mono whitespace-pre-wrap max-h-96 overflow-y-auto pr-2">
                    {article?.content || article?.description || 'Original text unavailable'}
                  </div>
                </div>

                <div className="bg-emerald-50/40 border border-emerald-200 rounded-xl p-4 flex flex-col">
                  <span className="text-xs font-bold uppercase tracking-wider text-emerald-800 mb-2 flex items-center gap-1">
                    <Sparkles className="w-3.5 h-3.5 text-emerald-600" />
                    FinNews AI Simplified Translation
                  </span>
                  <div className="space-y-3 max-h-96 overflow-y-auto pr-2">
                    <p className="text-sm font-semibold text-slate-900">{simplified.headline}</p>
                    <ul className="space-y-1.5 text-xs text-slate-700">
                      {simplified.tldr.map((t, idx) => (
                        <li key={idx} className="flex items-start gap-1.5">
                          <span className="text-emerald-600 font-bold">•</span>
                          <span>{t}</span>
                        </li>
                      ))}
                    </ul>
                    <div className="p-3 bg-white rounded-lg text-xs text-slate-700 italic border border-emerald-100 shadow-2xs">
                      "{simplified.eli5}"
                    </div>
                  </div>
                </div>
              </div>

              {/* Model Diagnostics */}
              <div className="p-3 bg-slate-50 border border-slate-200 rounded-lg flex items-center justify-between text-xs text-slate-500 font-mono">
                <span>Model Engine: {simplified.modelUsed}</span>
                <span>Latency: {simplified.processingTimeMs}ms</span>
                <span>Provider: {simplified.provider.toUpperCase()}</span>
              </div>
            </div>
          )}
        </div>

        {/* Footer */}
        <div className="p-4 border-t border-slate-200 bg-slate-50/80 flex items-center justify-between text-xs text-slate-500">
          <span className="flex items-center gap-1 font-medium text-emerald-700">
            <Check className="w-3.5 h-3.5 text-emerald-600" /> Factually grounded financial simplification
          </span>
          <button
            onClick={onClose}
            className="px-4 py-1.5 rounded-lg bg-slate-800 hover:bg-slate-900 text-white font-medium transition-colors cursor-pointer"
          >
            Close
          </button>
        </div>
      </div>
    </div>
  );
};
